settings:
  tool:
    breakSound: "minecraft:block.glass.break"
  inspect:
    # Set the cool down for the inspect tool (and command) in seconds
    cooldown:
      enabled: true
      time: 30
    # How many times the particles are spawned in. The particle shows for approx. 5 seconds
    iterations: 4
    # Should the milliseconds taken be shown in the message?
    showTimeTaken: true
    # Should the particles be shown for a single player or everyone in the world?
    perPlayer: true
  # The light block recipe where each character in the shape corresponds to a material.
  # For air use a blank space. The recipe is a shaped recipe and each line corresponds to a line
  # in the crafting grid. Recipe can be 1-3 lines and 1-3 ingredients (including air) per line.
  # To change the recipe in the server, you must restart your server !!!
  recipe:
    enabled: true
    shape:
      - "PGP"
      - "GIG"
      - "PGP"
    ingredients:
      P: "GLASS_PANE"
      G: "GLOWSTONE"
      I: "IRON_NUGGET"
    amount: 4

# Configure the plugin messages, the message should always include all the %s as
# it's used to paste in information such as time. The messages won't work without them !!!
messages:
  general-no-permission: "§cNo permission!"
  general-no-build-permission: "§cNo permission to build here!"
  general-reload: "§eReloaded config!"
  gui-close-button: "§c§lClose"
  gui-light-level-menu-name: "Set Light Level"
  gui-light-level-button-name: "§6§lLight Level %s"
  gui-light-level-button-description: "§7Sets the light level\n§7to a power of %s/15\n§0 \n§eClick to apply!"
  inspect-highlight: "§eHighlighting %s light blocks around you§7%s"
  inspect-noblocks: "§cNo light blocks found nearby!"
  inspect-cooldown-wait: "§cYou must wait %s seconds before using this again..."
  inspect-tool-name: "§c§lLight Block Tool"
  inspect-tool-lore: "§7Lets you edit the light\n§7blocks with ease\n§0 \n§e§lL-CLICK §7to destroy\n§e§lR-CLICK §7to inspect\n§e§lSHIFT-L-CLICK §7to edit"