name: LightBlockZ
version: 1.0
main: com.itsazza.lightblockz.LightBlockZ
api-version: 1.17
authors: [ ItsAZZA ]
website: https://bcsn.us
commands:
  lightblockz:
    aliases: "lightblocks"
  test:
    aliases: []