name: LightBlockZ
version: 1.1.1
main: com.itsazza.lightblockz.LightBlockZ
api-version: 1.17
author: ItsAZZA
website: https://bcsn.us
commands:
  lightinspect:
    permission: "lightblockz.inspect.command"
  lighttool:
    permission: "lightblockz.tool"
  lightreload:
    permission: "lightblockz.reload"