name: LightBlockZ
version: 1.2.1
main: com.itsazza.lightblockz.LightBlockZ
api-version: 1.17
author: ItsAZZA
website: https://bcsn.us
libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib:1.4.32'
commands:
  lightinspect:
    permission: "lightblockz.inspect.command"
  lighttool:
    permission: "lightblockz.tool"
  lightreload:
    permission: "lightblockz.reload"